Updates for version 1.3
JGCRI/demeter pull request #33
Opened 2022-10-10 18:52 UTC by kanishkan91

1. Take out transition code to increase memory allocation
2. Add parallelization for land type kernel density processing
3. Add post processing script to generate ncdf files corresponding to demeter runs with each LC as a subdata type
4. Add testing script for new users

2022-11-19 03:26 UTC, marideeweber approved these changes
As a python amateur, I was able to successfully run demeter and view the outputs, as well as modify the spatial resolution and run it again. There were hiccups at the beginning due to package version issues, but those have been resolved by changing which package versions are required. Great work!

2023-01-04 13:12 UTC, crvernon requested changes
Great job @kanishkan91!  Just a few inline comments to see to.  

Also, for the test data:  let's stay away from pickled files and use parquet files instead. Pickled files carry version dependencies. 

Thanks!

2023-01-04 13:12 UTC, crvernon commented on demeter/weight/kernel_density.py
> +def handle_single_pft(pft_order, order_rules, final_landclasses, pft_maps, cellindexresin,
This is a good time to start writing doc strings that will help us auto build documentation.  So one format that you could use would be the following:

```python
from typing import List, Union

import pandas as pd


def my_function(some_dataframe: pd.DataFrame,
                some_list_of_strings: List[str],
                some_list_of_ints: List[int],
                some_dictionary: dict,
                some_int_with_nonetype_default: Union[None, int] = None) -> dict:
    """This is a demo function that shows how to properly format a function and docstring that conforms to PEP8 
    requirements. The calculations in this function are rubbish and meant for demonstration purposes only.
    
    Parameters:
        some_dataframe (pd.DataFrame): The DataFrame used in calculations
        some_list_of_strings (List[str]): A list of strings used in calculations
        some_list_of_ints (List[int]): A list of integers used in calculations
        some_dictionary (dict): A dictionary used in calculations
        some_int_with_nonetype_default (Union[None, int]): An optional integer value with a default of None

    Returns:
        dict: A dictionary with the corresponding values calculated based on the input parameters
        
    """
    
    # get the max value of a field in the data frame
    max_rubbish_int = some_dataframe["rubbish"].max()
    
    # get use the max int of rubbish to get some item
    int_in_list = some_list_of_ints[max_rubbish_int]
    
    # get the corresponding string
    str_in_list = some_list_of_strings[max_rubbish_int]
    
    # get the corresponding dictionary value
    dict_value = some_dictionary[str_in_list]
    
    # get the int value if not none
    if some_int_with_nonetype_default is None:
        return {str_in_list: int_in_list + dict_value}
    
    else:
        return {str_in_list: int_in_list + dict_value + some_int_with_nonetype_default}
                
                
```

2023-01-04 13:12 UTC, crvernon commented on demeter/weight/kernel_density.py
> +    # print(pft_maps.shape)
remove all commented out code

2023-01-04 13:12 UTC, crvernon commented on demeter/weight/kernel_density.py
> +    min_seed = 0.0000000001
this should be a default for an argument in the function

2023-01-07 05:59 UTC, kanishkan91 commented on demeter/ncdf_conversion.py
> +if __name__ == "__main__":
Fixed. Thanks!

2023-01-07 06:03 UTC, kanishkan91 commented on demeter/process.py
> +        #self.transitions = np.zeros(shape=(self.l_spat_region, self.l_order_rules, self.l_order_rules))
Fixed. Thanks!

2023-01-07 06:04 UTC, kanishkan91 commented on demeter/process.py
> +         #   self.config.logger.info("Saving land cover transition files for time step {0}...".format(self.step))
Fixed. Thanks!

2023-01-07 06:05 UTC, kanishkan91 commented on demeter/process.py
> +          #  wdr.write_transitions(self.s, self.config, self.step, self.transitions)
Fixed. Thanks!

2023-01-07 06:06 UTC, kanishkan91 commented on demeter/process.py
> +                                self.config.metric, self.config.tabular_units, self.write_outputs,write_ncdf,self.sce,self.res,write_csv,self.regrid_res)
Fixed. Thanks!

2023-01-07 06:08 UTC, kanishkan91 commented on processing_scripts/convert_csv_col_to_ncdf_subdata.py
> +import xarray as x
I think this file itself is redundant since this has been functionalized. I'l take this out.

2023-01-07 06:08 UTC, kanishkan91 commented on processing_scripts/convert_csv_col_to_ncdf_subdata.py
> +
I think this file itself is redundant since this has been functionalized. I'l take this out.

2023-01-07 06:10 UTC, kanishkan91 commented on processing_scripts/demeter_processing.py
> +import demeter
Fixed. Thanks

2023-01-07 06:10 UTC, kanishkan91 commented on setup.py
>                        'pandas~=1.2.4',
Fixed. Thanks!

2023-01-07 06:14 UTC, kanishkan91 commented on .github/workflows/build.yml
>              pip install pandas==1.2.4
Fixed. Thanks!

2023-01-07 13:17 UTC, kanishkan91 commented on demeter/tests/data/inputs/mapping/gcam_basin_lookup.csv
> +basin_id,basin_name,glu_name
As mentioned in the code, the new inputs are parameterized. The package data under demeter/data are no longer required. These inputs are specific to the tests.

2023-01-07 13:17 UTC, kanishkan91 commented on demeter/tests/data/inputs/mapping/gcam_regions_32.csv
> +gcam_region_id,gcam_region_name
As mentioned in the code, the new inputs are parameterized. The package data under demeter/data are no longer required. These inputs are specific to the tests.

2023-01-07 13:23 UTC, kanishkan91 commented on demeter/weight/kernel_density.py
> +def handle_single_pft(pft_order, order_rules, final_landclasses, pft_maps, cellindexresin,
Done. Thanks!

2023-01-08 03:49 UTC, kanishkan91 commented on demeter/weight/kernel_density.py
> +    # print(pft_maps.shape)
Done. Thanks!

2023-01-08 03:49 UTC, kanishkan91 commented on demeter/weight/kernel_density.py
> +    min_seed = 0.0000000001
Will save this for the next release. I have added a TODO in the code

2023-01-08 03:50 UTC, kanishkan91 commented on demeter/weight/kernel_density.py
> +    # apply image filter
Done. Thanks

2023-01-08 03:52 UTC, kanishkan91 commented on demeter/weight/kernel_density.py
> +        pool.starmap(handle_single_pft, zip(aux_val,repeat(order_rules),repeat(final_landclasses),
Done. And yes, its all in pycharm

2023-01-08 03:52 UTC, kanishkan91 commented on processing_scripts/convert_csv_col_to_ncdf_subdata.py
> +
Yes. As mentioned above going to take this out

2023-01-08 04:10 UTC, merged